### PR TITLE
Blog cards color restored

### PR DESCRIPTION
**Pull request by goyalmuskan**

### CODE REVIEW

**Comment by abhu-A-J** [comment]
@goyalmuskan I made the hearts red on purpose and not orange! @smaranjitghose

**Comment by goyalmuskan** [comment]
I changed the heading color, I guess the hearts were in the same class. I’ll correct it with the contact us page.

**Comment by goyalmuskan** [comment]
Also, you changed the font-family, that’s why I didn’t change it back, I don’t understand  what’s the need to point it out here?

**Comment by goyalmuskan** [comment]
Also, I didn’t just change the colors, I added the blogs css back which you deleted I guess.

**Comment by abhu-A-J** [comment]
> Also, you changed the font-family, that’s why I didn’t change it back, I don’t understand what’s the need to point it out here?

Because this is no way hard level.

You changed the heart's color here. they were styled seperately.
Screenshot (115)

**Comment by abhu-A-J** [comment]
> > Also, you changed the font-family, that’s why I didn’t change it back, I don’t understand what’s the need to point it out here?
> 
> Because this is no way hard level.
> 
> You changed the heart's color here. they were styled seperately.
> Screenshot (115)

@smaranjitghose Sir mind looking into this??

**Pull request merged**
