### PR TITLE
Team Page fixed

### PR DESCRIPTION
**Pull request by goyalmuskan**
I have fixed some spacing issues, made the font of the webpage consistent with the website and the footer is also fixed.

### CODE REVIEW

**Comment by shreyakapoor08** [comment]
@goyalmuskan I have mentioned it under Issue #191 That I am working on this issue.
The space issues.

@smaranjitghose Kindly look into it.

**Comment by goyalmuskan** [comment]
Hello @shreyakapoor08, I was also assigned to work on the teams page, didn’t know you were working as well. 😅

**Comment by goyalmuskan** [comment]
201655FE-3AD5-4B6B-8023-2296583A25F1

This still needs to be fixed if you are working on this page @shreyakapoor08

**Comment by shreyakapoor08** [comment]
> Hello @shreyakapoor08, I was also assigned to work on the teams page, didn’t know you were working as well. 😅

I have mentioned it there itself.
It would be great if you too mention the specific points you are working on beforehand :)

**Comment by goyalmuskan** [comment]
> > Hello @shreyakapoor08, I was also assigned to work on the teams page, didn’t know you were working as well. 😅
> 
> I have mentioned it there itself.
> It would be great if you too mention the specific points you are working on beforehand :)

Sure 😊

**Pull request merged**
