### PR TITLE
Add particle effect in the parallax section (on home page)

### PR DESCRIPTION
**Pull request by aman-atg**

### CODE REVIEW

**Comment by smaranjitghose** [comment]
Can you please illustrate the differences between the current version and your work. Use screenshots or gifs

**Comment by aman-atg** [comment]
> Can you please illustrate the differences between the current version and your work. Use screenshots or gifs

Oh sorry for that.

**Comment by aman-atg** [comment]
### BEFORE 
DeepinScreenshot_select-area_20200409174318
### AFTER
particle-js

**Comment by smaranjitghose** [comment]
Nice work @aman-atg

**Pull request merged**
