### PR TITLE
Restyling faq

### LINKED ISSUE #412: Restyling FAQ
*Screenshots of the proposed changes compared with the current version of the project
image

### PR DESCRIPTION
**Pull request by shreyakapoor08**
Fix #412 

1. Restyled the whole section.
2. Corrections in the answers done.
3. Additional question added.
image

### CODE REVIEW

**Comment by shreyakapoor08** [comment]
@smaranjitghose @anushbhatia Kindly check :)

**Comment by shreyakapoor08** [comment]
@smaranjitghose Kindly check :)

**Comment by shreyakapoor08** [comment]
@anushbhatia Okay, Kindly merge this one. I will add the cards in the next PR

**Comment by anushbhatia** [comment]
Make in this only why another pr

**Comment by shreyakapoor08** [comment]
okay

**Comment by shreyakapoor08** [comment]
> Have cards for this section like homepage so that it looks good.

@anushbhatia I have added the cards and changed the css too. Please check if any changes are required :)
image

This is how it is looking

**Comment by shreyakapoor08** [comment]
> Don't use green and orange together

image

**Pull request merged**
