### PR TITLE
Home Page documentation

### PR DESCRIPTION
**Pull request by shreyakapoor08**
Fix #554 

image

@smaranjitghose Kindly check :)

### CODE REVIEW

**Comment by smaranjitghose** [comment]
Certain changes:

- For stuff like path names or even lines of code, use [literal blocks](https://thomas-cokelaer.info/tutorials/sphinx/rest_syntax.html) like:

```python
print("Hello World")
```

or ```assets\Images|\..````
- For selecting color, give a line you can select your color using Google's [color picker](https://www.google.com/search?q=color+picker&oq=color+picker&aqs=chrome..69i57j0l7.4228j0j1&sourceid=chrome&ie=UTF-8)
and also we need the hex value

- Increase spacing between points

- For the files, required to edit give external links (i.e. links to the files on this repo's master branch)

**Comment by shreyakapoor08** [comment]
@smaranjitghose I have made all the changes which you told. Please review and let me know if something else is required till here :)

**Comment by smaranjitghose** [comment]
> @smaranjitghose I have made all the changes which you told. Please review and let me know if something else is required till here :)

docs/_build/html/_sources/```index.rst.txt```

I think the files are supposed to be in .rst extension instead of plain text. just do a ```make html``` changing that. If everything works fine, make those changes otherwise let it be

**Comment by shreyakapoor08** [comment]
I will just recheck

**Comment by shreyakapoor08** [comment]
I have done it, and it is the same. 
within the source directory its extension is. rst.txt only

**Comment by shreyakapoor08** [comment]
> I have done it, and it is the same.
> within the source directory its extension is. rst.txt only

image

**Pull request merged**
