### PR TITLE
added gitCret action

### PR DESCRIPTION
**Pull request by aashimgarg**
This GitHub Action automatically commits files which have been changed during a Workflow run and pushes the commit back to GitHub.

Add gitCret to actions folder.

Issue related  #122

### CODE REVIEW

**Comment by aashimgarg** [comment]
@smaranjitghose review it.

**Comment by aashimgarg** [comment]
@smaranjitghose please review it.

**Comment by smaranjitghose** [comment]
Can you please elaborate on the situations when this will be useful?

**Comment by aashimgarg** [comment]
It prevents pushing sensitive keys or the credentials and it continuously scan your repositories, commits or pull-requests for sensitive credentials and generate alerts.

So i think it will be very usefull @smaranjitghose

**Comment by smaranjitghose** [comment]
Awesome!

**Pull request merged**
