### PR TITLE
footer styling

### LINKED ISSUE #409: Footer bug
**Description of the enhancement**
Some content is visible below the footer in contact us page

**Screenshots**
Screenshots of the proposed changes compared with the current version of the project
image

### PR DESCRIPTION
**Pull request by shreyakapoor08**
Fix #409 
1. Restyled the footer.
2. Responsive corrections
3. Removed depreciated tags
image

### CODE REVIEW

**Comment by shreyakapoor08** [comment]
@smaranjitghose Kindly check. I have made the changes as you said

**Comment by smaranjitghose** [comment]
footer

- Adjust these please
- Try to change the toggle button to something else

**Comment by shreyakapoor08** [comment]
image

Kindly check

**Comment by shreyakapoor08** [comment]
> footer
> 
> * Adjust these please
> * Try to change the toggle button to something else

Sure :)
Kindly merge this one. I will do the other changes in the next PR

**Pull request merged**
