### PR TITLE
 Page not found design

### PR DESCRIPTION
**Pull request by Adyasha8105**
This PR solves #256 
Here, I have used Adobe XD and Illustrator to make this design.

### CODE REVIEW

**Comment by anushbhatia** [comment]
Screenshot_20200411_160212_com android chrome
It's not showing anything please share the screenshot too

**Comment by Adyasha8105** [comment]
screenshot

**Comment by Adyasha8105** [comment]
screenshot 2

**Comment by anushbhatia** [comment]
Screenshot_20200411_184724_com android chrome
Don't take the content directly modify the elements if u are using them

**Comment by Adyasha8105** [comment]
No no, I have change style.

**Comment by smaranjitghose** [comment]
Did you just make the template or actually changed the port to redirect it.?
I tried looking into this. But couldn't fetch it @anushbhatia Please verify this

**Comment by Adyasha8105** [comment]
> Did you just make the template or actually changed the port to redirect it.?
> I tried looking into this. But couldn't fetch it @anushbhatia Please verify this

I just only make the template.

**Pull request closed without merging**
