### PR TITLE
Dynamic team cards injection

### PR DESCRIPTION
**Pull request by abhu-A-J**
addresses #744 

Merge #746  first to avoid code loss.

Uses #746 to inject cards dynamically to the team page to improve scalibility

### CODE REVIEW

**Comment by abhu-A-J** [comment]
> Increase the time in which all the images get loaded

They are lazy-loaded right now, and doing that will make page slow Sir.
Also since they are static images from internal paths we can't delay the requests made it is done via browsers only and if we force it it can cause abnormal behavior, don't you think?

**Comment by anushbhatia** [comment]
We can't force it, ofcourse but can't lazy loading work faster as it increases the time for loading on the complete page.that's not preferred by browsers

**Comment by abhu-A-J** [comment]
> We can't force it, ofcourse but can't lazy loading work faster as it increases the time for loading on the complete page.that's not preferred by browsers

No it works just when user viewports match browsers viewport, hence we place a placeholder image (viewports in the sense when we scroll enough to match the image's line of reference)

There can be one solution where first three images can be avoided to be lazy-loaded if that's what you want to view directly independent of scroll.

**Comment by anushbhatia** [comment]
ok then let me discuss with @smaranjitghose and let you know what we will do

**Comment by smaranjitghose** [comment]
> ok then let me discuss with @smaranjitghose and let you know what we will do

There won't be any considerable difference for our project in terms of loading time even if the images are loaded from internal paths, the amount of assets loaded is not large enough that we need to incorporate this

**Comment by abhu-A-J** [comment]
> > ok then let me discuss with @smaranjitghose and let you know what we will do
> 
> There won't be any considerable difference for our project in terms of loading time even if the images are loaded from internal paths, the amount of assets loaded is not large enough that we need to incorporate this

What about JS Dyanmic cards injection? That helps in scalibility ! I can remove lazy load if that's not needed!
@smaranjitghose Sir, what do you think? Also the website currently has lazy loading on team page! 
I am just making it dynamic so avoid wirting and copy pasting HTML again and again

**Comment by abhu-A-J** [comment]
Resolved conflicts on the page!

**Comment by abhu-A-J** [comment]
Sir that it how lazy loading works. Show image only when line of reference matches.
It's the same behaviour like which the website has on team page in current version, this PR is just injecting them using JS to make them dynamic ( for scaling application) that's all.

**Comment by abhu-A-J** [comment]
> See you have done a great work in making a JSON format in so just remove the lazy loader and let rest of code remain there

Finally Done Sir! I have removed lazy load as you mentioned 🚀 . Let me know if any more changes are needed!

**Comment by anushbhatia** [comment]
Great Work!!!

**Pull request merged**
