### PR TITLE
added hover effect

### PR DESCRIPTION
**Pull request by aashimgarg**
added the hoverEffect on the images on the index.html file.

### CODE REVIEW

**Comment by aashimgarg** [comment]
Screenshot from 2020-04-10 18-10-48

@smaranjitghose have a look.

**Comment by smaranjitghose** [comment]
@aashimgarg Nice work with the hover effect.
Please ensure that the text in it is at the centre

**Comment by aashimgarg** [comment]
> @aashimgarg Nice work with the hover effect.
> Please ensure that the text in it is at the centre

Ok @smaranjitghose .

**Comment by aashimgarg** [comment]
Screenshot from 2020-04-10 18-49-01

@smaranjitghose done!

**Comment by smaranjitghose** [comment]
Awesome

**Pull request merged**
