### PR TITLE
Team Page Added

### LINKED ISSUE #7: Team Page
Create a Team Page with animations like this:
https://dscvit.com/team.html

### PR DESCRIPTION
**Pull request by SaranshDawra**
Fixes #7 

@smaranjitghose Please review this pull request.

### CODE REVIEW

**Comment by anushbhatia** [comment]
Team page looks great just one issue, link it to the navbar to all links presents
add footer also.

clean design and proper implementation.

great work, keep it up!!

**Comment by SaranshDawra** [comment]
@anushbhatia I have updated the navbar links as asked.

**Comment by anushbhatia** [comment]
Linking has failed try adding it to the latest version deployed

**Comment by SaranshDawra** [comment]
@anushbhatia It is working. Only announcements and blog links won't work as the pages aren't added yet.

**Comment by anushbhatia** [comment]
use the latest file

**Comment by SaranshDawra** [comment]
@anushbhatia Please review.

**Comment by anushbhatia** [comment]
navbar on the team page should be the same as that on  the team one

**Comment by SaranshDawra** [comment]
@anushbhatia Navbar updated, please check.

**Pull request merged**
