### PR TITLE
:star: Improvment in achievement page

### LINKED ISSUE #287: Card Optimization in achievements page
Use Proper Symbols in this.
Remove the red line present in the card and Girlscript Chennai heading

### PR DESCRIPTION
**Pull request by ashishnagpal2498**
fixes #287 
Card overlapping on button show more , corrected.
Chevron Icons added instead of span.
Toggle improved.
Removed span code.
Before -
image
After -
image

### CODE REVIEW

**Comment by anushbhatia** [comment]
Smaller icons for it and icon colour should be white when it drops down.

**Comment by ashishnagpal2498** [comment]
Done @anushbhatia .

**Comment by anushbhatia** [comment]
not completely center aligned

**Comment by ashishnagpal2498** [comment]
Done @anushbhatia  
image

**Comment by ashishnagpal2498** [comment]
I think what I did in this PR was of "hard difficulty level" as it was tough to handle buttons through JS. Could you please upgrade the level of this PR @anushbhatia ?

**Comment by smaranjitghose** [comment]
Sure, have a talk with @anushbhatia regarding this

**Pull request merged**
