### PR TITLE
Navbar-fixed

### LINKED ISSUE #35: Change the Navbar
- Add logo
- Change the font 
- Increase the width
if possible use better colours with them.

### PR DESCRIPTION
**Pull request by Yashank18**
Fixes #35 

Files Changed: - index.html and style.css

Changes Made:
1)Height of navbar
2)Logo
3)Mobile view Fixed
4)On hover Effect

Please check @anushbhatia and @smaranjitghose 

@goyalmuskan Please refer to changes so that there should be no merge issues.

### CODE REVIEW

**Comment by anushbhatia** [comment]
https://www.eggradients.com/category/orange-gradient?83ff460c_page=2
refer this for gradient or the official website of 
https://www.gssoc.tech/

increase the size of the logo
Don't use fluorescence in the navbar content.
Do something like this

**Comment by Yashank18** [comment]
Okay @anushbhatia

**Comment by Yashank18** [comment]
@anushbhatia  Please check

**Comment by anushbhatia** [comment]
- Which tab is activated just highlight that link
- on clicking log redirect to index.html 
- reduce the size of navbar like on contact us on scrolling down

**Comment by Yashank18** [comment]
Okay

**Comment by Yashank18** [comment]
@anushbhatia, as requested the color of link, should get changed which is active but here these are just external links.

**Comment by anushbhatia** [comment]
so what's the problem in that just refer to bootstrap documentation and :active function for it.

**Comment by anushbhatia** [comment]
Resolve these issues rest everything is fine

**Pull request merged**
