### PR TITLE
React: Add Footer Component

### PR DESCRIPTION
**Pull request by rabeehrz**
Add Footer component to React Version.

View here: https://girlscript-chennai-website-deploy.now.sh/

### CODE REVIEW

**Comment by rabeehrz** [comment]
@anushbhatia I can't seem to reproduce this issue on my system. Any idea why this is happening? I don't have that problem on my system. Is anyone else experiencing the same issue?

**Comment by rabeehrz** [comment]
@anushbhatia I've checked it out on Windows and macOS. I didn't find any problem. If you know what is causing this issue, do let me know. 😄

**Comment by anushbhatia** [comment]
Got it because of transition it is doing this in one case the transition escape's screen size

**Comment by rabeehrz** [comment]
> Got it because of transition it is doing this in one case the transition escape's screen size

I'll check it out. Do you know which screen size? I took the code from the master branch. Maybe is happens there as well?

**Comment by anushbhatia** [comment]
it works if u add a text tag

**Pull request merged**
