### PR TITLE
Improve achievement data

### PR DESCRIPTION
**Pull request by himanshusharma89**
@smaranjitghose @ousnik 
Resolved issue: #101

### CODE REVIEW

**Comment by himanshusharma89** [comment]
image
image
image

**Comment by smaranjitghose** [comment]
It is for displaying achievements of members, we don't need keynote or event

**Comment by himanshusharma89** [comment]
Hey @smaranjitghose , can I know why this PR is closed?

**Comment by smaranjitghose** [comment]
I already specified above that it is not  need for Achievements page, if you wish you can do it for Announcements page

**Comment by himanshusharma89** [comment]
Okay, I’ll make a PR for that.

**Pull request closed without merging**
