### PR TITLE
Different Navbar bug fixes

### PR DESCRIPTION
**Pull request by abhu-A-J**
**Navbar Bug Fix**

- the hamburger icon is blended into the background (normal mode) (not visible to users )
- the home page is not set as an active state by default in both modes (mobile view) (when we open page for the first time) - updates only when clicked on it
- the active state in dark mode is blended in backgrounds (not visible)
- update vendors (enhancement ) 
Fix Used:
Styling changes and additions of toggler hamburger

### CODE REVIEW

**Comment by Adyasha8105** [comment]
> **Navbar Bug Fix**
> 
> * the hamburger icon is blended into the background (normal mode) (not visible to users )
> * the home page is not set as an active state by default in both modes (mobile view) (when we open page for the first time) - updates only when clicked on it
> * the active state in dark mode is blended in backgrounds (not visible)
> * update vendors (enhancement )
>   Fix Used:
>   Styling changes and additions of toggler hamburger

@abhu-A-J I am happy to see that you are solving all the bugs but I am working on it, it will be better if you solve all the bugs after all my PR.

**Comment by abhu-A-J** [comment]
> > **Navbar Bug Fix**
> > 
> > * the hamburger icon is blended into the background (normal mode) (not visible to users )
> > * the home page is not set as an active state by default in both modes (mobile view) (when we open page for the first time) - updates only when clicked on it
> > * the active state in dark mode is blended in backgrounds (not visible)
> > * update vendors (enhancement )
> >   Fix Used:
> >   Styling changes and additions of toggler hamburger
> 
> @abhu-A-J I am happy to see that you are solving all the bugs but I am working on it, it will be better if you solve all the bugs after all my PR.

But you don't have any PR's open on navbar? And there is also no issue related to it. And your PR #782 also doesn't mention an issue number so how would I know that you are assigned or not?
Also your PR  says fixed the navbar in both modes! 
So I saw the issue while looking at the website and made a PR

**Comment by Adyasha8105** [comment]
> > > **Navbar Bug Fix**
> > > 
> > > * the hamburger icon is blended into the background (normal mode) (not visible to users )
> > > * the home page is not set as an active state by default in both modes (mobile view) (when we open page for the first time) - updates only when clicked on it
> > > * the active state in dark mode is blended in backgrounds (not visible)
> > > * update vendors (enhancement )
> > >   Fix Used:
> > >   Styling changes and additions of toggler hamburger
> > 
> > 
> > @abhu-A-J I am happy to see that you are solving all the bugs but I am working on it, it will be better if you solve all the bugs after all my PR.
> 
> But you don't have any PR's open on navbar? And there is also no issue related to it. And your PR #782 also doesn't mention an issue number so how would I know that you are assigned or not?
> Also your PR says fixed the navbar in both modes!
> So I saw the issue while looking at the website and made a PR

Ya but I am working on both the enhancement If you face any issue like that you can create an issue of it if mentor assigns you then you can go for it.

**Comment by abhu-A-J** [comment]
> > > > **Navbar Bug Fix**
> > > > 
> > > > * the hamburger icon is blended into the background (normal mode) (not visible to users )
> > > > * the home page is not set as an active state by default in both modes (mobile view) (when we open page for the first time) - updates only when clicked on it
> > > > * the active state in dark mode is blended in backgrounds (not visible)
> > > > * update vendors (enhancement )
> > > >   Fix Used:
> > > >   Styling changes and additions of toggler hamburger
> > > 
> > > 
> > > @abhu-A-J I am happy to see that you are solving all the bugs but I am working on it, it will be better if you solve all the bugs after all my PR.
> > 
> > 
> > But you don't have any PR's open on navbar? And there is also no issue related to it. And your PR #782 also doesn't mention an issue number so how would I know that you are assigned or not?
> > Also your PR says fixed the navbar in both modes!
> > So I saw the issue while looking at the website and made a PR
> 
> Ya but I am working on both the enhancement If you face any issue like that you can create an issue of it if mentor assigns you then you can go for it.

How how would I know that you're working on it is the issue? 🤣 
Coming on slack to discuss!

**Comment by Adyasha8105** [comment]
> > > > > **Navbar Bug Fix**
> > > > > 
> > > > > * the hamburger icon is blended into the background (normal mode) (not visible to users )
> > > > > * the home page is not set as an active state by default in both modes (mobile view) (when we open page for the first time) - updates only when clicked on it

Ya point but how can you do a direct PR of it like you should create an issue of it and if anyone has objection he/she will comment on that.

**Comment by abhu-A-J** [comment]
> > > > > > **Navbar Bug Fix**
> > > > > > 
> > > > > > * the hamburger icon is blended into the background (normal mode) (not visible to users )
> > > > > > * the home page is not set as an active state by default in both modes (mobile view) (when we open page for the first time) - updates only when clicked on it
> 
> Ya point but how can you do a direct PR of it like you should create an issue of it and if anyone has objection he/she will comment on that.

and you should also try not to leave bugs behind or mention on PR I has left this part out since I want to make a new PR for it as the issue was very bug for single PR.

**Comment by anushbhatia** [comment]
Guys make an issue first before making a PR.

**Comment by abhu-A-J** [comment]
@anushbhatia Sir will surely do. 
But I had no idea navbar was undergoing a major UI change and after my dynamic cards got merged I updated my fork and saw this and made a correction. I had no idea Adyesha was working on it to correct mistkes after her PR got merged, I thought it's a bug missed out/not addressed hence the PR. 

Will create issues from next time :thumbsup

**Comment by anushbhatia** [comment]
Relax see basically nowadays you guys directly make a pr for bugs so I was thinking of creating an issue named bugs and you list bugs there.

**Pull request closed without merging**
