### PR TITLE
:star: contact us page

### LINKED ISSUE #290: Improvement in Contact us page.
I want to improve the CSS of contact us page. It is looking empty as compared to other pages.
image

### PR DESCRIPTION
**Pull request by ashishnagpal2498**
fixes #290 
Contact us page with image ---
Before 
image

After
image

### CODE REVIEW

**Comment by anushbhatia** [comment]
Make the corners of the form round.

**Comment by ashishnagpal2498** [comment]
@anushbhatia , You want the contact us page to be like this

> 
> 
> Make the corners of the form round.
> The right side looks empty
>

**Comment by anushbhatia** [comment]
Yes

**Comment by ashishnagpal2498** [comment]
Hey @anushbhatia , I was working on this issue.

**Pull request closed without merging**
