### PR TITLE
added SEO optimization for the registration page

### PR DESCRIPTION
**Pull request by aashimgarg**
added SEO optimization for the registration page.

1. Added necessary meta tags to the page.
2. added stylesheets which were required.
3. gave it proper indentation.

Worked on #566 .

### CODE REVIEW

**Comment by abhu-A-J** [comment]
hey @aashimgarg I'm still working on SEO of pages! Including the meta tag chain. You may work on other optimization required as Sir said in one of previous PR's or you may let me know on slack in future if you're doing so!

**Comment by aashimgarg** [comment]
> hey @aashimgarg I'm still working on SEO of pages! Including the meta tag chain. You may work on other optimization required as Sir said in one of previous PR's or you may let me know on slack in future if you're doing so!

i asked him before doing this.

**Comment by abhu-A-J** [comment]
> > hey @aashimgarg I'm still working on SEO of pages! Including the meta tag chain. You may work on other optimization required as Sir said in one of previous PR's or you may let me know on slack in future if you're doing so!
> 
> i asked him before doing this and there are still many pages left. you can work on all of those!

Cool! I didn't know that! Sorry about that! I had no idea on that!

**Comment by aashimgarg** [comment]
> > > hey @aashimgarg I'm still working on SEO of pages! Including the meta tag chain. You may work on other optimization required as Sir said in one of previous PR's or you may let me know on slack in future if you're doing so!
> > 
> > 
> > i asked him before doing this and there are still many pages left. you can work on all of those!
> 
> Cool! I didn't know that! Sorry about that! I had no idea on that!

you can delete your comment now.

**Pull request merged**
