### PR TITLE
Making Announcement Page Responsive #303

### PR DESCRIPTION
**Pull request by Kashish-max**
Resolves issue #303

### CODE REVIEW

**Comment by Kashish-max** [comment]
Screenshot (88)

Screenshot (89)

Screenshot (90)

Screenshot (91)

Screenshot (96)

Screenshot (94)

Screenshot (93)

Screenshot (92)

**Comment by Kashish-max** [comment]
I have also removed unwanted and repeated code

**Comment by goyalmuskan** [comment]
@smaranjitghose @Kashish-max I was assigned to work on this. 😅

**Comment by Kashish-max** [comment]
I'm really sorry @goyalmuskan but it was 3 days and I thought you forgot about this issue. Don't worry lots of new issues are there every day.

**Comment by Kashish-max** [comment]
Sir please review this

**Comment by anushbhatia** [comment]
**Don't Work on any issue until not assigned.**

**Comment by Kashish-max** [comment]
Sorry @anushbhatia sir please assign me if required after @goyalmuskan's PR.

**Pull request closed without merging**
