### PR TITLE
Custom Error message in the form of toast

### LINKED ISSUE #794: Bugs
Any bugs coming up in project should be mentioned here and the person will be assigned to resolve it.
You can also help or assist the person already working on an issue by mentioning the error here.

### PR DESCRIPTION
**Pull request by Adyasha8105**
Fix #794 
I have added the custom error message according to the questions.
Next:- Responsive and colors(dark mode)

@anushbhatia Please check it :)

### CODE REVIEW

**Comment by aashimgarg** [comment]
@anushbhatia i was working on this!!

**Comment by abhu-A-J** [comment]
I think the issue was closed? Why are you guys making PR's for closed issue. I think there's ton of work left  on react pages and very few people working on it.  we all  should work on it and try to complete it ?
What say @anushbhatia Sir?

**Comment by aashimgarg** [comment]
> I think the issue was closed? Why are you guys making PR's for closed issue. I think there's ton of work left on react pages and very few people working on it. we all should work on it and try to complete it ?
> What say @anushbhatia Sir?

Actually i was working on the other two parts of the issue as she said she was working on the first and the last one but she sended the PR for this one two.

**Comment by Adyasha8105** [comment]
> I think the issue was closed? Why are you guys making PR's for closed issue. I think there's ton of work left on react pages  and very few people working on it. we all should work on it and try to complete it  ?
> What say @anushbhatia Sir?

I think @anushbhatia mistakenly close that issue as the bug is not solved and I don't know react that much. And about the bug issue as you and your other two member are working on the react page  so I think may be you didn't get enough time to work on this bug issue that's why I have solved that by consulting to the mentor. It's been 4 days given that issue to him. And you have rightly said we all should work on it and try to complete it. So am just  doing it :)

**Comment by anushbhatia** [comment]
See those who know react can continue working on it till then this is just enhancements we are making

**Pull request merged**
