### PR TITLE
Images added

### PR DESCRIPTION
**Pull request by shreyakapoor08**
Images added related to the respective achievements
image

### CODE REVIEW

**Comment by shreyakapoor08** [comment]
@anushbhatia I have searched and found these images related to the achievement section. Kindly check.

**Comment by shreyakapoor08** [comment]
@anushbhatia Kindly check
image

**Comment by shreyakapoor08** [comment]
@anushbhatia it's the same image which i have added i guess

**Comment by anushbhatia** [comment]
it's square so u don't have to squeeze the image

**Comment by shreyakapoor08** [comment]
actually I set the height of all the images so that cards are of same size. 
Should i put the picture as it is without setting the height?

**Comment by anushbhatia** [comment]
yep use this image without setting height

**Comment by shreyakapoor08** [comment]
@anushbhatia Here it is :)
image

**Comment by anushbhatia** [comment]
ok then keep it like this

**Comment by shreyakapoor08** [comment]
@anushbhatia, okay! 
Kindly merge it

**Pull request merged**
