### PR TITLE
Announcements Page Updated

### PR DESCRIPTION
**Pull request by goyalmuskan**
Screenshot (90)

Screenshot (89)

Screenshot (88)

### CODE REVIEW

**Comment by anushbhatia** [comment]
The button used in the upcoming events remove the border when we do not hover it.
In recent events remove the grey border instead add box-shadow.
use a bolder font for the headings Upcoming events and recent events.

**Comment by goyalmuskan** [comment]
> The button used in the upcoming events remove the border when we do not hover it.
> In recent events remove the grey border instead add box-shadow.
> use a bolder font for the headings Upcoming events and recent events.

Okayy

**Comment by smaranjitghose** [comment]
@goyalmuskan  Make the changes and give another PR.
Also for the Recent events, just take the content from GirlScript's official website like Uplift Project etc, make it up a bit if required and put it

**Comment by goyalmuskan** [comment]
> @goyalmuskan Make the changes and give another PR.
> Also for the Recent events, just take the content from GirlScript's official website like Uplift Project etc, make it up a bit if required and put it

Okayy

**Pull request merged**
