### PR TITLE
Feature/btn enhancement

### LINKED ISSUE #286: Button Enhancement all over the project
Use the same kind of drop shadow all over the project 
Have round rectangular corners
radius: 6-8
x:0
y:3
b:6

Before giving a pr just send the image here

### PR DESCRIPTION
**Pull request by ashishnagpal2498**
fixes #286 
Consistency of button shadow and radius all over the project.
image
image

### CODE REVIEW

**Comment by anushbhatia** [comment]
Both of you have given a pr for this

**Comment by ashishnagpal2498** [comment]
Hi @anushbhatia , I have made the necessary changes.
image

**Comment by anushbhatia** [comment]
No, this effect looks better

**Comment by ashishnagpal2498** [comment]
> 
> 
> No, this effect looks better

Which 1 ?

**Comment by anushbhatia** [comment]
the current button on hover increases drop shadow around that's better and minimal

**Pull request closed without merging**
