### PR TITLE
removed jQuery calls as its slim calls are already made

### PR DESCRIPTION
**Pull request by aashimgarg**
removed jQuery calls as its slim calls are already made in every page.

### CODE REVIEW

**Comment by smaranjitghose** [comment]
@aashimgarg  Please fix the merge conflict

**Comment by Muskan-Mangal** [comment]
@aashimgarg actually minified version was required for fadeIn and fadeOut function of jquery to work.
Without that scroll with fadeIn and fadeout won't work too.
Just have a look at the console..
Screenshot from 2020-04-28 12-01-12
@smaranjitghose Please review the dependencies clearly, It may cause problem.

**Comment by aashimgarg** [comment]
> @aashimgarg actually minified version was required for fadeIn and fadeOut function of jquery to work.
> Without that scroll with fadeIn and fadeout won't work too.
> Just have a look at the console..
> Screenshot from 2020-04-28 12-01-12
> @smaranjitghose Please review the dependencies clearly, It may cause problem.

I will look in this. thanks for the info.

**Comment by Muskan-Mangal** [comment]
@aashimgarg , Since this is affecting the scroll to top functionality that I implemented, So I am working on this now. Please don't make any changes related to that . I have been assigned for that.
Hope u will corporate :)

**Pull request merged**
