### PR TITLE
Events page

### LINKED ISSUE #72: Events Page
Create a page like the one uploaded
Events

You can play with colours

### PR DESCRIPTION
**Pull request by abhu-A-J**
fixes #72 

@anushbhatia I have made the following changes:
- Completed designed the events page
- Designed the navbar with hamburger style menu for smaller devices
- Custom styling on page (no use of external css libraries like bootstrap)
- Complete responsiveness
- Slight hover and shadow effects to enhance UX
- Colors are used based on GirlScript colors itself ( it's slightly different from the issue image provided)
The route to trigger it will be: `/events/`

I have kept all the work under events folder to avoiding styles with other pages.

The working is as follows:
ezgif com-optimize

### CODE REVIEW

**Comment by anushbhatia** [comment]
Make the cards little bigger

Add z index to button use better colors with it.

**Comment by abhu-A-J** [comment]
> Make the cards little bigger
> 
> Add z index to button use better colors with it.

@anushbhatia Sir, I have made the changes, I have made cards bigger along with adding redish color to buttons

**Comment by anushbhatia** [comment]
link it to the current navbar

**Comment by abhu-A-J** [comment]
> link it to the current navbar
Do you mean replace the navbar with the one on the index.html page??

**Comment by abhu-A-J** [comment]
> link it to the current navbar

@anushbhatia Sir, I completely misunderstood what you were trying to say above,  so I actually ended up replacing the custom navbar I built (without bootstrap on the events page) with the bootstrap navbar similar to the home page. 
Also, I have added the link to events page on the home page which was actually want you wanted. You can review and let me know about the changes. Thanks!

**Comment by anushbhatia** [comment]
make this same as home navbar
just increase the size of the current links to bold

**Comment by abhu-A-J** [comment]
@anushbhatia Sir, I have made the navlinks bolder on events page as you mentioned .

**Comment by anushbhatia** [comment]
Add events link to rest of pages too
Like contacts us achievements blog page etc

**Comment by abhu-A-J** [comment]
> Add events link to rest of pages too
> Like contacts us achievements blog page etc
Sir, I have made the changes. Thanks! Sorry about so many silly mistakes.

**Comment by abhu-A-J** [comment]
> > Add events link to rest of pages too
> > Like contacts us achievements blog page etc
@anushbhatia  Sir, I have made the changes. Thanks! Sorry about so many silly mistakes.

**Pull request merged**
