### PR TITLE
changes to home page

### PR DESCRIPTION
**Pull request by raniyer**
1) Add animation to the image slider behind "welcome to GirlsScript Chennai"
2) rectify the flipped card error. See image.
3) remove the extra space
4) add subheading to the icons

Please let me know of my flaws and what I could improve more.
Thank you.

### CODE REVIEW

**Comment by anushbhatia** [comment]
Try to reduce the size of the images so that they can be loaded faster!

**Comment by raniyer** [comment]
@anushbhatia please review the changes.

Only one image was resixed (1st image of carousel) since every other image on that page was already under 1000X1000 pixels. On further minimizing, it would have led to display degradation.

**Comment by smaranjitghose** [comment]
@raniyer Please have a look at the current code base and give a Pull Request. There are multiple PRs

**Comment by raniyer** [comment]
@smaranjitghose hey, I tried resolving merge conflicts. It shows no conflicts now.
I am still new to this, so forgive me if i didn't understand somethings.

**Pull request merged**
