### PR TITLE
Added Board Members

### LINKED ISSUE #191: Team Page
Please share a screenshot with an elaborate description of what part you want to improve on or any bug you wish to fix

### PR DESCRIPTION
**Pull request by shreyakapoor08**
Fixes #191 

Board Members are added
image

### CODE REVIEW

**Comment by anushbhatia** [comment]
Add the names too

**Comment by shreyakapoor08** [comment]
@anushbhatia Added names

**Comment by smaranjitghose** [comment]
Can you please fix the alignment error for the ```Management Team``` section in the next PR

**Comment by shreyakapoor08** [comment]
sure, I will do that

**Pull request merged**
