### PR TITLE
Cover image template for girl script

### LINKED ISSUE #213: UI/UX Tasks
- Create a custom logo for the project that represents the concepts of open-source,code and the actual GirlScript Foundation logo
- Create a preview image for the repository (1280×640) with the key ideas mentioned above

### PR DESCRIPTION
**Pull request by Adyasha8105**
This PR closes #213 .
Here, I have made a cover image template for GirlScript using Adobe XD and Illustrator.

### CODE REVIEW

**Comment by anushbhatia** [comment]
reduce the image of file website will have problems pulling it

**Comment by Adyasha8105** [comment]
> reduce the image of file website will have problems pulling it

Now You can check it.

**Comment by smaranjitghose** [comment]
It is too large for the publication header, please do some google search or use your medium account to resize it appropiately

**Comment by Adyasha8105** [comment]
> It is too large for the publication header, please do some google search or use your medium account to resize it appropiately

@smaranjitghose  What should be the size range???

**Comment by anushbhatia** [comment]
Max 1-2mb use any image optimizer available on Internet have the quality around 80%

**Comment by Adyasha8105** [comment]
> Max 1-2mb use any image optimizer available on Internet have the quality around 80%

I have resized the images (less than 1mb).
Is it ok now sir @anushbhatia ?

**Pull request merged**
