### PR TITLE
 :darkMode: -feat(achievementsPage)!

### PR DESCRIPTION
**Pull request by aashimgarg**
darkMode for achievementsPage

### CODE REVIEW

**Comment by aashimgarg** [comment]
@anushbhatia have a look!

**Comment by aashimgarg** [comment]
Screenshot from 2020-04-19 16-39-48

they are showing!

**Comment by anushbhatia** [comment]
ezgif com-crop
U can see here

**Comment by aashimgarg** [comment]
> ezgif com-crop
> U can see here

ohk i got it heading is only coming after the mouseLeave function.

**Pull request merged**
