### PR TITLE
Enabling Dark Mode

### PR DESCRIPTION
**Pull request by sakshi1499**
Dark Mode enabled in all pages.

Issue encountered : flip not working in homepage.

(team femmetech) @sonalsk

### CODE REVIEW

**Comment by anushbhatia** [comment]
change the logo in this section and try to add better colours to it.
and it's having this issue to just check it once
https://drive.google.com/drive/folders/1V3NW8SqzgRDPi4oBQbqgZc9PmKOGEDyu?usp=sharing


change the colors of them

**Comment by sakshi1499** [comment]
Strangely, Its completely fine in my development environment. Can you please tell me which browser you are using? @anushbhatia 

gs_logo

**Comment by anushbhatia** [comment]
Chrome browser only

**Comment by sakshi1499** [comment]
I am using mozilla, that is why the difference @anushbhatia

**Comment by sakshi1499** [comment]
Can you verify it on Firefox? If fine, I'll add those changes in chrome as well

**Comment by sakshi1499** [comment]
I saw the video, this is also not occurring in firefox. PS. The chrome rendering is slightly displaced too
image


There is an extra tile of image.What do you think should be done?

**Comment by anushbhatia** [comment]
How have u converted the elements of the website by coding each of them or something different?

**Comment by sakshi1499** [comment]
Actually, chrome recently started supporting mix-blend-mode so there might be bugs. What we can do is that we can force the image to remain same and also the header can be shrunk a little bit so its not visible. @anushbhatia If we can't do this, there is certainly no way to implement dark mode without npm packages then or react maybe.

**Comment by anushbhatia** [comment]
check the website of dsc vit they have implemented dark mode too. I can give the code of the whole website if u want. 
https://dscvit.com/

**Comment by sakshi1499** [comment]
Send me the code, I'll see😊

**Comment by anushbhatia** [comment]
https://drive.google.com/drive/folders/1V3NW8SqzgRDPi4oBQbqgZc9PmKOGEDyu?usp=sharing

**Comment by sakshi1499** [comment]
@anushbhatia We can't do that. This website is in sections with different colors and not just white and just black, what they have done is dsc vit website is just to implement a toggle function which will change all white to black and all black to white. For that to happen, we would have to makeover the whole website.

**Comment by anushbhatia** [comment]
I will discuss bout this issue with my team and tell u.

**Pull request closed without merging**
