### PR TITLE
blog page enhancements.

### PR DESCRIPTION
**Pull request by aashimgarg**
Enhanced the design of the blog card.

Before:-

Screenshot from 2020-04-11 16-25-19

After:-

Screenshot from 2020-04-11 16-25-01

@smaranjitghose have a look.

### CODE REVIEW

**Comment by shreyakapoor08** [comment]
@aashimgarg Hey, this is already improved and merged. Kindly take the pull from master again.
image

**Comment by aashimgarg** [comment]
> @aashimgarg Hey, this is already improved and merged. Kindly take the pull from master again.
> image

My branch is even with master. You can check the website yourself.

**Comment by aashimgarg** [comment]
@shreyakapoor08 my branch is even with the master. heck the website yourself.

**Comment by shreyakapoor08** [comment]
> @shreyakapoor08 my branch is even with the master. Check the website yourself.
> I can upload a screenshot if you want.

image

**Comment by aashimgarg** [comment]
Screenshot from 2020-04-11 17-30-15

**Comment by shreyakapoor08** [comment]
maybe it is showing differently in windows and Ubuntu. Please check your branch in windows as well. If it is affecting their or not

**Comment by aashimgarg** [comment]
> maybe it is showing differently in windows and Ubuntu. Please check your branch in windows as well. If it is affecting their or not

i did not have any merge conflicts either while submitting the PR. if my branch was not even there would be some merge conflicts.

**Comment by shreyakapoor08** [comment]
@aashimgarg I am not talking about merhe conflicts. I am just saying is your changes working fine in windows as well? just check that

**Comment by aashimgarg** [comment]
sorry i just work on ubuntu.

**Comment by aashimgarg** [comment]
@smaranjitghose please have a look.

**Comment by anushbhatia** [comment]
Web content has no relation to os understand this

**Comment by aashimgarg** [comment]
> Web content has no relation to os understand this

any idea why the changes were not displaying in my browser.

**Comment by smaranjitghose** [comment]
The name of the author being highlighted in orange is very creepy.  And the last PR had already resolved the extra space in the bottom which is now back again.

**Comment by aashimgarg** [comment]
> The name of the author being highlighted in orange is very creepy. And the last PR had already resolved the extra space in the bottom which is now back again.

@smaranjitghose  any idea why the changes are not displaying in the firefox browser.

**Pull request merged**
