### PR TITLE
Modified Contact page 

### LINKED ISSUE #334: Responsive and modified contact page
I just want to change the design of the contact page.

### PR DESCRIPTION
**Pull request by Adyasha8105**
I just modified the contact page style.
This PR closes #334

### CODE REVIEW

**Comment by anushbhatia** [comment]
add this address and everything I will provide add an image and then a black layer of 60-70 opacity try  making something like this

**Comment by Adyasha8105** [comment]
@anushbhatia @smaranjitghose Need any changes?

**Comment by anushbhatia** [comment]
Reduce the size of the text and user a lighter font below the headings

**Comment by smaranjitghose** [comment]
@Adyasha8105 Try to make the contactUs page responsive with the current changes

**Comment by Adyasha8105** [comment]
> @Adyasha8105 Try to make the contactUs page responsive with the current changes

ya sir after merging this PR, I will do the responsive part.

**Pull request merged**
