### PR TITLE
Added label Workflow

### PR DESCRIPTION
**Pull request by himanshusharma89**

### CODE REVIEW

**Comment by anushbhatia** [comment]
why have u deleted a page

**Comment by himanshusharma89** [comment]
> why have u deleted a page

@anushbhatia That file is not related to the workflow of github actions

**Comment by anushbhatia** [comment]
announcement page.html is not required?

**Comment by himanshusharma89** [comment]
> announcement page.html is not required?

I just added an action...It is a commit from the previous PR. So I removed it. It will not affect anything.

**Comment by smaranjitghose** [comment]
> > announcement page.html is not required?
> 
> I just added an action...It is a commit from the previous PR. So I removed it. It will not affect anything.

Don't commit that then na. Your PR removes the Announcements Page completely. I have cross verified in the netlify deploy for the PR

**Comment by himanshusharma89** [comment]
Okay, I am fixing it.

**Comment by himanshusharma89** [comment]
> > > announcement page.html is not required?
> > 
> > 
> > I just added an action...It is a commit from the previous PR. So I removed it. It will not affect anything.
> 
> Don't commit that then na. Your PR removes the Announcements Page completely. I have cross verified in the netlify deploy for the PR

Done, check it now

**Pull request merged**
