### PR TITLE
Success confetti on registration

### LINKED ISSUE #651: Enhancement of confetti in Achievements
I wanted to have something like [Link](https://twitter.com/i/status/1000968725158244352)

### PR DESCRIPTION
**Pull request by abhu-A-J**
closes #651 
Addresses point 2 .
Addition of confetti as a celebration for registering successfully 

Mentors kindly review the same! 
The form needs to be completed to get the confetti celebration (as per issue)
https://deploy-preview-827--girlscriptboilerplate.netlify.app/registrations.html

### CODE REVIEW

**Comment by anushbhatia** [comment]
Try using blue colour on the confetti I referred
'

**Comment by abhu-A-J** [comment]
> Try using blue colour on the confetti I referred
> '

Do you want all of them as blue Sir ? or just the blue ones to change colors?

**Comment by abhu-A-J** [comment]
> Try using blue colour on the confetti I referred
> '

Done Sir! USed the same blue as reference given

**Comment by anushbhatia** [comment]
[https://codepen.io/orrybaram/pen/LxOMwG](https://codepen.io/orrybaram/pen/LxOMwG) use this confetti here and

**Comment by abhu-A-J** [comment]
Does this work Sir?, this is the closest I could get to the codepen link without copying the code !

Screenshot (195)

**Pull request merged**
