### PR TITLE
Content added

### LINKED ISSUE #356: Achievement section
**Description of the enhancement**
Dummy content to be replaced with actual content

**Screenshots**
Screenshots of the proposed changes compared with the current version of the project
Screenshot_2020-04-15-23-05-36-727_com android chrome

@smaranjitghose can i work on it?

### PR DESCRIPTION
**Pull request by shreyakapoor08**
Fix #356 
image

### CODE REVIEW

**Comment by shreyakapoor08** [comment]
@anushbhatia Kindly add labels to it

**Comment by anushbhatia** [comment]
Really Sorry.
Make another pr and add images related to it also

**Comment by shreyakapoor08** [comment]
okay 😊

**Comment by shreyakapoor08** [comment]
@anushbhatia Hey Please add gssoc20 label here. I am not able to see updated marks

**Pull request merged**
