### PR TITLE
Fixed bug on team page and made it consistent with other pages

### PR DESCRIPTION
**Pull request by abhu-A-J**
addresses **part 3** of #191 

The PR does the following:

- The navbar is made consistent with other pages in terms of styling.
- All the heading are made consistent with all the other pages
- All the buttons are made consistent with other pages
- Removed unnecessary CDN's.
- Added the go to top action button which was not present and got it functioning like other pages

**SCREENSHOTS**
- Go to top button and working
Team Page

- Navbar consistency:
Screenshot (94)

- Header consistency
Screenshot (95)

- Buttons consistency
Screenshot (96)
Screenshot (97)

### CODE REVIEW

**Comment by anushbhatia** [comment]
Add box-shadow to show all button and add a subtle gradient like
##### Button Gradient #FE824A #FE824A -> #E16831 #E16831

**Comment by abhu-A-J** [comment]
> Add box-shadow to show all button and add a subtle gradient like
> 
> ##### Button Gradient #FE824A #FE824A -> #E16831 #E16831

Thank's @anushbhatia Sir, I'll do the same!

**Comment by anushbhatia** [comment]
Increase the size of the button and reduce the border-radius to 7

**Comment by abhu-A-J** [comment]
> Increase the size of the button and reduce the border-radius to 7

**Comment by abhu-A-J** [comment]
@smaranjitghose Sir, @anushbhatia Sir, hope they're okay now!! thanks

Screenshot (100)

**Pull request merged**
