### PR TITLE
change the style of button

### LINKED ISSUE #286: Button Enhancement all over the project
Use the same kind of drop shadow all over the project 
Have round rectangular corners
radius: 6-8
x:0
y:3
b:6

Before giving a pr just send the image here

### PR DESCRIPTION
**Pull request by Adyasha8105**
This PR closes #286.

### CODE REVIEW

**Comment by Adyasha8105** [comment]
Actually I haven't seen that a participant had already made that PR.
And there are some changes here which are not present in his PR.

**Comment by anushbhatia** [comment]
Send the screenshot of button

**Comment by Adyasha8105** [comment]
> Send the screenshot of button

**Comment by Adyasha8105** [comment]
Here I just change the color of the border and name, same as other.
i.e black to orange

**Comment by anushbhatia** [comment]
wait I will give u an example
Adobe XD 12-04-2020 01_03_17 (2)
Something of this kind 
Don't make it dull
[https://www.gssoc.tech/](https://www.gssoc.tech/) Look through there about us page.

**Comment by ashishnagpal2498** [comment]
Hey @anushbhatia @smaranjitghose , the issue was assigned to me as well and I gave my PR  #304 before this PR.

**Comment by anushbhatia** [comment]
Ok see there's an error at the blog page and many places there u can enhance them. We see quality over quantity here.

**Pull request merged**
