### PR TITLE
Medium Blogs integrated

### PR DESCRIPTION
**Pull request by goyalmuskan**
Screenshot (127)

#285

### CODE REVIEW

**Comment by anushbhatia** [comment]
Screenshot_20200412_113629_com android chrome
Optimize this for mobile too

**Comment by goyalmuskan** [comment]
Done @anushbhatia

**Comment by anushbhatia** [comment]
add better orange colour to the button and add margin spacing so that there's a breathing space present.

**Comment by goyalmuskan** [comment]
Done @anushbhatia

**Pull request merged**
