### PR TITLE
added darkMode.

### PR DESCRIPTION
**Pull request by aashimgarg**
i added a darkMode in index.html using a togglerButton.

related #335

### CODE REVIEW

**Comment by aashimgarg** [comment]
have a look @anushbhatia @smaranjitghose

**Comment by anushbhatia** [comment]
Refer
https://material.io/design/color/dark-theme.html#usage
https://dscvit.com/
Refer to these for colours and still if u face any issue just dm me on slack.

**Comment by aashimgarg** [comment]
@anushbhatia I messaged you on slack.

**Comment by aashimgarg** [comment]
Made the icons white in darkMode.
fixed the shadow of the buttons.

@anushbhatia have a look!!!

**Comment by anushbhatia** [comment]
great work!!!

**Comment by aashimgarg** [comment]
In the footer?

**Comment by aashimgarg** [comment]
@anushbhatia done!

**Pull request merged**
