### PR TITLE
added github action to automatically rebase a pr

### PR DESCRIPTION
**Pull request by aashimgarg**
this pr adds the github action to automaticaaly rebase a pr.

work on #122

### CODE REVIEW

**Comment by aashimgarg** [comment]
@smaranjitghose please review it.

**Comment by smaranjitghose** [comment]
Can you please elaborate on the situations when this action will be useful?
(Elaborate more on rebasing a PR)

**Comment by aashimgarg** [comment]
When you rebase, Git finds the base of your branch,finds all the commits between that base and HEAD and re-plays those commits on the HEAD of the branch you're rebasing onto. Git actually creates new commits that represent what your changes look like on top of master

**Comment by smaranjitghose** [comment]
Cool!

**Pull request merged**
