### PR TITLE
alligned button perfectly

### PR DESCRIPTION
**Pull request by Muskan-Mangal**
suggestions in issue #474 .
I have alligned the button perfectly. it's in the middle now.

Screenshot from 2020-04-29 00-26-08

### CODE REVIEW

**Comment by Muskan-Mangal** [comment]
@anushbhatia review it please!

**Comment by Muskan-Mangal** [comment]
I have alligned it but couldn't do the customization part. 
After closing this issue , I think we should make a different issue for this and let the volunteer work on customization.

**Comment by Adyasha8105** [comment]
> Make the toggle button functional in mobile too

@anushbhatia Actually me and @Muskan-Mangal both are working on this part. So merge her PR, I will work on the mobile view and give another PR of it.

**Comment by anushbhatia** [comment]
okay cool

**Pull request merged**
