### PR TITLE
Added blogs.html webpage

### PR DESCRIPTION
**Pull request by shreoshi-roy**
Added webpage for blogs section and linked all other webpages with it.
Solves issue #4

### CODE REVIEW

**Comment by anushbhatia** [comment]
check this issue


as well as use cards add z-index and improve the UI of it.

**Comment by smaranjitghose** [comment]
@shreoshi-roy please update your repo with the current version of the codebase before giving PRS

**Comment by shreoshi-roy** [comment]
I sent a new PR #89. That is updated . Please review .

**Comment by shreoshi-roy** [comment]
Added another PR #92 as some more changes were pushed few hours ago

**Pull request closed without merging**
