### PR TITLE
extra space removed

### PR DESCRIPTION
**Pull request by rajraman786**
there is extra space in anouncement page that is removed .
now its look better

### CODE REVIEW

**Comment by anushbhatia** [comment]
Please share the screenshot

**Comment by smaranjitghose** [comment]
@rajraman786 Please make sure there are no merge conflicts

**Comment by rajraman786** [comment]
here are the screenshots of removig extra space in anouncement page.
announce

**Comment by rajraman786** [comment]
and here is the screenshots of modifying
blog1
blog2

 blog page.

**Comment by smaranjitghose** [comment]
I don't recall assigning you the Blog page?

**Comment by rajraman786** [comment]
> 
> 
> I don't recall assigning you the Blog page?
sir,
      sorry for that as I am new here. so, please guide me on what I do further.

**Comment by rajraman786** [comment]
> 
> 
> @rajraman786 Please make sure there are no merge conflicts

thankyou 
now I resolved all the conflicts.

**Comment by smaranjitghose** [comment]
@rajraman786,
Please see the current [version](https://girlscriptchennai.netlify.com/announcements.html). Your PR is messing up with the css of the page. Please rectify that and give another PR

**Comment by rajraman786** [comment]
> 
> 
> @rajraman786,
> Please see the current [version](https://girlscriptchennai.netlify.com/announcements.html). Your PR is messing up with the css of the page. Please rectify that and give another PR

sir, 
    I see the current version of announcement page and no doubt it is better than earlier. 
   but, i think the earlier top part is quite much good. i want the to add the top part.
 please assigned me.

**Pull request closed without merging**
