### PR TITLE
:feat: => budget.json 

### PR DESCRIPTION
**Pull request by aashimgarg**
Added budget.json to increase the web app performance.

It supports three types of budgets:-

1. Timing budgets: Assert thresholds for time-based performance metrics like First Contentful Paint,  
    Maximum First Input Delay, and Speed Index.
2. Resource counts: Assert thresholds for the quantity of resources on a page. These thresholds can
    be defined per resource type or for the page overall.
3. Resource sizes: Assert thresholds for the transfer size of resources on a page. These thresholds    
    can be defined per resource type or for the page overall.

It is required to increase the web app performance.

Related to #519

### CODE REVIEW

**Comment by anushbhatia** [comment]
@abhu-A-J has already added one

**Comment by aashimgarg** [comment]
> @abhu-A-J has already added one

@anushbhatia no.

**Comment by abhu-A-J** [comment]
@aashimgarg Brother @anushbhatia Sir this looks like lighthouse budget config file. I think this is good but we need to run a lighthouse npm package or equivalent actions to make it work, so it goes beyond the scope of tools here (npm).
Also ticking to budget is very hard since all the pages keep on changing!
More info can be found here: https://web.dev/use-lighthouse-for-performance-budgets/

**Comment by abhu-A-J** [comment]
> @abhu-A-J has already added one

No Sir, I added something sort of similar which gives details similar to it, but it's not budget. We have to analyze the script ourselves wherein the budget it will be generating it on running a script
I haven't added budgeting on it since it needs additional tooling like either usage of npm lighthouse package or lighthouse actions.
and people with no node.js installed cannot run them and also npm was not mentioned in the scope of the project,

**Comment by abhu-A-J** [comment]
> > @abhu-A-J has already added one
> 
> Yes Sir, I added something sort of similar which gives details similar to it, but it's not budget. We have to analyze the script ourselves wherein the budget it will be generating it on running a script
> I haven't added budgeting on it since it needs additional tooling like either usage of npm lighthouse package or lighthouse actions.
> and people with no node.js installed cannot run them and also npm was not mentioned in the scope of the project,

**Comment by anushbhatia** [comment]
@aashimgarg so after completing the project we can minimize this and reduce the scripts and CSS to as less as possible

**Comment by abhu-A-J** [comment]
> @aashimgarg so after completing the project we can minimize this and reduce the scripts and CSS to as less as possible

We can run scripts like uglify-css, concatenation of css and compression so achieve the same.

**Comment by aashimgarg** [comment]
> @aashimgarg so after completing the project we can minimize this and reduce the scripts and CSS to as less as possible

yes.

**Comment by anushbhatia** [comment]
You can update this now

**Pull request closed without merging**
