### PR TITLE
added git auto commit action

### PR DESCRIPTION
**Pull request by aashimgarg**
This GitHub Action automatically commits files which have been changed during a Workflow run and pushes the Commit back to GitHub.

work on #122

### CODE REVIEW

**Comment by aashimgarg** [comment]
@smaranjitghose please review it

**Comment by smaranjitghose** [comment]
Please Elaborate on the working and the situations when this Action comes handy

**Comment by aashimgarg** [comment]
The purpose of this GitHub action is to auto-commit back any changes made to the branch through previous GitHub actions.
If no changes are detected, the Action does nothing.

**Comment by aashimgarg** [comment]
@smaranjitghose please review it

**Comment by smaranjitghose** [comment]
I would like to use git bash for this rather

**Pull request closed without merging**
