### PR TITLE
Team page enhancement (2)

### LINKED ISSUE #690: Team Page (Enhancement)
- [x] Change the UI to Add Parallex Depth to the cards for each member
Refer [this](https://codepen.io/andymerskin/full/XNMWvQ)
- [x] Each member should have options to include Linkedin,GitHub
- [ ] Team Division: Board, Technical Team, Marketing Team, Creatives Team,Publicity Team

__For any Pull Request you give, including relevant comments is mandatory for review__

### PR DESCRIPTION
**Pull request by Adyasha8105**
Fix #690 
- I have added the dark mode theme.
- I have made the navbar the same as others.
- I have aligned the cards (3 in one row).
- I have removed some of the errors.

### CODE REVIEW

**Comment by abhu-A-J** [comment]
@Adyasha8105 let prettier auto format code! You seem have given 2 spaces and it with 2 tabs as prettier is configured with!

**Comment by Adyasha8105** [comment]
> @Adyasha8105 let prettier auto format code! You seem have given 2 spaces and it with 2 tabs as prettier is configured with! It was added so we don't have to add spaces manually it's super tiring and unnecessary 🤣

But the prettier format is not doing that. so that's why I have done that as Kashish made the prev PR so some CSS have spaces and others not so I have done that manually :) .

**Comment by abhu-A-J** [comment]
> > @Adyasha8105 let prettier auto format code! You seem have given 2 spaces and it with 2 tabs as prettier is configured with! It was added so we don't have to add spaces manually it's super tiring and unnecessary 🤣
> 
> But the prettier format is not doing that. so that's why I have done that as Kashish made the prev PR so some CSS have spaces and others not so I have done that manually :) .

Go to the bottom of VS code and choose indent using tabs (it will show as configured as an option) choose that and it will be indented automatically!

**Comment by anushbhatia** [comment]
it is showing 2

**Pull request merged**
