### PR TITLE
refactor achievement HTML

### PR DESCRIPTION
**Pull request by ashishnagpal2498**
Issue #263 
Code quality Improvement -
1) Refactored - achievement.html - 
  - Removed JS from in between ✅ 
  -  Function used instead of jQuery ready.
  - Removed redundant CDNs 🔁 
  - Used CSS instead of JS for simple hover.

Will be working on each and every file step by step. Merge gradually.
Advisable - Not to merge any PR till tomorrow as it might create conflict.
@anushbhatia

### CODE REVIEW

**Comment by anushbhatia** [comment]
See there are still changes to be made, So wait for them and then you can go on

**Comment by ashishnagpal2498** [comment]
Okay, no problem. But my suggestion would be, lets improve the whole thing today itself as changes will keep on coming, day by day. What's say? @anushbhatia

**Comment by anushbhatia** [comment]
okay then do it at the end of the day when all PRs are merged.

**Comment by ashishnagpal2498** [comment]
> 
> 
> okay then do it at the end of the day when all PRs are merged.

Okay, merge all the PR's and create an announcement - "Not to create a PR till tuesday" , I will complete all the file changes tomorrow i.e. refactor whole project. Cool ?

**Comment by anushbhatia** [comment]
yes, no problem but message me when u make a PR on slack

**Comment by ashishnagpal2498** [comment]
Okay , I have started working on this.

**Pull request merged**
